name: Deploy File

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create deployment directory
        run: |
          mkdir deploy
          cp output.txt deploy/

      - name: Deploy to gh-pages branch
        run: |
          cd deploy
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy output.txt"
          git push --force origin gh-pages
